:PROPERTIES:
:ID:       cf6d4ff3-5654-4c9a-9854-f9d0e78d6ebf
:END:
#+title: 2020-10-01 Once a month

* Ru
Wake & Sport: Научился подтягиваться больше пары раз, на флэте уехал backroll to revert. Начал катать по фигурам, разучил пару новых элементов. Джиббинг по началу даётся проще, чем флэт. Скоро сезон уже пора закрывать(

Streams: Первый стрим, который набрал 200 просмотров меньше, чем за неделю. Юбилейное количество попдисавшихся людей, целых 128! В остальном всё по-прежнему, движемся неспешно) Подался на EmacsConf 2020 с темой последнего стрима, в октябре должен прийти ответ.

RDE: Более менее расшарил основы никса, дописал конфиги для основных своих хостов, хотя ещё нужно часть вещей разнести по модулям, сделал шаблон воспроизводимого окружения для python с возможностью пакетировать и деплоить. Запилил модуль, который позволяет генерить воспроизводимый конфиг для emacs, нужно изменить одну концептуально важную хрень, но в целом работает отлично.

Изрядно поигравшись с никсом всё чаще натыкаюсь на так себе задизайненые моменты, всё больше ловлю себя на мысли, что вроде nix (язык) не так уж и плох, но было бы лучше иметь general purpose язычёк, да? Возможно настало время и я уже готов для Guix?

Есть ещё мысли/новости, которыми хочу поделиться, но запилю отдельные посты или может быть нет)
