:PROPERTIES:
:ID:       c68bfd42-b2eb-4332-93d9-5a31e1aeda42
:ROAM_ALIASES: "Backpacking Gear"
:END:
#+title: Tourist Equipment

* First Equipment
- Trekking boots
- Backpack
- Tent
- Sleeping bag
- Sleeping mat
- Flashlight
- Membran jacket
- Gas burner
- Trekking poles
- Water filter
- Knife

* Backpack
- https://durstongear.com/products/kakwa-55 + [[https://youtu.be/G1S1cP21tiU][Back Ventilation Solution]].
- https://zpacks.com/products/arc-haul-ultra-60l-backpack.

Transition from arc haul to kakwa-40 + alpha wool and other stuff:
https://youtu.be/Pl5-ZKdUCzo
* Shoes
Lowa - interesting boots brand.
Luna Sandals - Vibram Flip flops.

* Trekking Poles
[[https://www.komperdell.com/en/Camera-Staff-PL/K1762300-10-Tele][Komperdell Camera Staff PL]] 294g

* Clothes
https://www.decathlon.com.tr/p/erkek-uzun-kollu-tisort-merinos-yunu-lacivert-mt500/_/R-p-301659?mc=8501956

* Camping Tent
- [[https://www.naturehike.com/products/naturehike-vik-series-970g-ultralight-15d-nylon-single-tent-nh18w001-k?variant=36760140349594][Naturehike VIK-1]]. 1.6kg

[[https://www.naturehike.com/collections/towel/products/naturehike-camping-sport-quick-drying-cooling-microfiber-towel][Naturehike Towel]]. 70g + bag.

[[https://aliexpress.ru/item/1005004016616043.html][3F UL GEAR Lanshan Pro]]

* Sleeping
** Bag/Quilt
naturehike cw300 - bag
[[https://aliexpress.ru/item/32824587744.html][AEGISMAX G1]]
https://www.garagegrowngear.com/products/revelation-850fp-by-enlightened-equipment

** Pad
lixada - condensate

thermarest neoair xthem - pad
https://www.rei.com/product/199935/nemo-tensor-ultralight-insulated-sleeping-pad
[[https://aliexpress.ru/item/1005001698879456.html][Blackdeer Archeos Light]]
** Pillow
- [[https://www.backcountry.com/nemo-equipment-inc.-fillo-elite-pillow][Fillo Elite Pillow]]
- [[https://www.amazon.com/Exped-Pillow-Camping-Travel-Large][Exped Mega Pillow]]

* Washing
https://www.naturebuffsoap.com/shop :: small soap in a net + zipper bag.

* Knife
Simple, but durable.
https://morakniv.ru.com/products/kansbol

* Multitool
https://ileatherman.ru/multitul-leatherman-squirt-ps4-black-831233

* Flashlight / Headlamp
WIZARD PRO NICHIA
[[https://www.amazon.com/dp/B0CBL5R8KG?tag=justinoutdo0c-20&keywords=black%2Bdiamond%2Bdeploy&geniuslink=true&th=1][BLACK DIAMOND Deploy Run Light]]

* Sneakers
Crocs, suitable for watersports?
https://www.crocs.ru/catalog/muzhchinam/obuv/krossovki-i-lofery/#item-680608

* Socks
Waterproof
https://dexshell.ru/vodonepronicaemye-noski--dexshell-coolvent-ague-blue-ds628/

* Kitchen
[[https://aliexpress.ru/item/4000799843939.html][Spoon/fork]]
[[https://www.garagegrowngear.com/products/nanodry-trek-towel-small-by-matador?variant=40843662786747][NanoDry Trek Towel (Small) by Matador]]

* To sort
NH18D020-Z палки карбоновый трекинговые
BRS3000T горелка
https://ileatherman.ru/multitul-leatherman-style-cs-831245
TREK 100 FORCLAZ пуховка из декатлона

* Links
https://youtu.be/gD_nobywJnw
https://youtu.be/EigFgZOpsG8 :: nice sleeping setup and a few more useful items.
https://youtu.be/F5NANSiznNo :: full UL setup.
https://youtu.be/8ZZgcNWIlJ4 :: 10 ultralight gear by some backpacking girl.
http://jupiterhikes.com/gear/ :: UL gear list.
https://youtu.be/_Luv47rRla4 :: a good least of equipment for each category.
https://youtu.be/nmrVk4KGJkg :: three UL setups (backpack, sleeping pad, quilt, tent).
