:PROPERTIES:
:ID:       c889b790-06d6-4066-a994-4cf2026de909
:END:
#+title: Behavioral Evolution

Mostly notes for lections from [[*Materials][Materials]] section.

* Selections
** Individual selection
Trying to reproduce the gen as much as possible.

#+begin_quote
Sometimes a chicken is an egg's way of making eggs.
#+end_quote
*** Natural selection
Keeping the traits, which helped to survive and reproduce in population.
*** Sexual selection
Increasing the amount of traits in population prefered by opposite
sex. It can be very useless in terms of survival.

** Kin selection
Helps relatives (the same gen) to reproduce as much as possible, even
in to the own detriment.

** Reciprocal altruism
You scratch my back, I scratch yours. Can appear by utilizing kin
selection for a small isolated part of population to fix altruistic
traits in gene and spread it later to the whole population

** Killing for success
When male substitutes current alpha-male.
- Reduce a reproductive success of other male.
- Make female ovulate (doesn't ovulate, when nursing kid)
Doesn't have to kill, if the previous male was your relative.

** Spontaneously aborts
When another male substitute current alpha male, smell of new male
causes female to misscarry a litter. It helps to reproduce female's
genes, because it not necessary to spend resources on birth of an
infant, who will be killed by the new male, female can save a lot of
time and resources.

In other species male can harass pregnant female to make her
misscarry.

Another solution is pseudo-estrus to pretend that an infant is a child
of new male.

** The older the woman the more defensive she is
Young female doesn't want to get injured protecting her child. Older
female doesn't have a lot of options to pass her gens.

** The kidnapping
The lower-ranking guy can cover himself with a kid of higher ranking
guy in case of conflict.

** Intersex competitiong
Migrating males do not care about future reproductive success of
female and their imprinting genes make fetal development more active,
while female's imprinting genes make it slower to make it more safe
for her and make it possible to get a chance to reproduce in the
future.

** Increase of female in population during crysis
It less risky to give a birth to female.

** Toxic sperm
Some polyandry species have toxic sperm to reduce chances of other
males to reproduce.

** Puberty migration
Males for baboons, females for chimps => Higher agression in baboon
troops, higher probably of war for chimps, because their male cooperate.

* Cheating and Cooperation
Related to [[id:2e5e27be-9970-4b7b-9fe9-a2dfa4b3da03][Game Theory]].

Tit for tat is one of the best long-term stratagies in most
interactions. You start from cooperating, cheat if opponent cheated,
but forgive him and continue cooperating if he started to do it
again. But it vulnurable to noise (incorrect signal transmission).
Check [[id:7bc9cb52-d3bc-44d6-977e-9ede27589543][The Evolution of Trust]] for interactive example of
game and different stratagies.

Forgiving TFT is a solution for the noise problem, but it's vulnurable
to non-fogiving stratagies.

TFT -> TFTWF after few rounds of cooperation solves both problems.

[[https://www.lesswrong.com/posts/3rxMBRCYEmHCNDLhu/the-pavlov-strategy][Pavlov strategy]] can beat TFTWF.

Vampire bats using TFT strategy, when cooperatively feeding all the
kids of the group, they will stop feeding kids of one's mom if she
doesn't bring the blood for all kids.

The cool experiment with sticlkeback fish and mirrors. Cooperating and
cheating with reflections showing TFT strategy.

Gender-switching fish. Female pays more for act of reproduction. If in
a pair one of the fishes being male for too long, the other one
rejects to cooperate. TFT again.

Lions prides don't do TFT. It can be a scary cat in the pride, which
hides after the backs of others most of the time and don't get
punished for that.

Naked mole rats. There are a few big fat rats, which eats a lot and do
nothing almost all the time, but during the rain the plug the entry to
the tunnels. In real world we play many prisoner's dilemma games at
the time.
*
|                        | Big guys     | Same as women           |
|------------------------+--------------+-------------------------|
| Aggression             | +++          | +                       |
| Access to reproduction | 5% have kids | 95% have 2 kids         |
| Sexual dimorphism      | +            | -                       |
| What women wants       | Big          | Paternal                |
| Parenting              | +            | +++                     |
| Lifespan (male2female) | <            | =                       |
| Twins                  | -            | +                       |
| Female abandon kids    | -            | +                       |
| Female cheating        | -            | +                       |
| Spicies name           | Tournament   | Monogamous/Pair bonding |

Originally most of the cultures allowed polygamy, however most of
people were monogamous/pair bonding.

* Noteable facts
** We are better at detecting cheating than kindness.
75% vs 25%.

* Materials
- [[https://youtu.be/Y0Oa4Lp5fLE][2. Behavioral Evolution]]
- [[https://youtu.be/oKNAzl-XN4I][3. Behavioral Evolution II]]
