:PROPERTIES:
:ID:       17ae244d-076e-4735-8e67-4e2c952d8465
:END:
#+title: Handstand Diary

* 2024-01-16
I have pretty good physique, but almost no experience with handstand.

I had a lot of attempts (more than 100) to stand, but they were hugely
spreaded in time and I was never focused on this element.

Right now I can stand a few seconds with legs apart a bit.  I feel
weakness in my wrists, which are intensively used for balancing.  When
my lower back bended it becomes hard to balance.  Sperading legs apart
makes it easier to engage the lower back and keep balance.  When there
is a deflection in lower back it's hard to engage core/abdominal
muscles.

Got a coupl seconds of full hand stand, I balance forward with wrist
and backward with bending my elbows.

I take couple minutes between each attempt to fully recover my power.

Bending fingers helps to balance and reduce strain on wrists.

I had quite intensive warmup: https://youtu.be/hgNcfzTxvO8.  Did 5
sets of 10-20 seconds handstand trying to bounce off the wall.  I need
more adaptation in the wrists, probably can reach it by standing in
front of the wall and holding one foot on the wall.

* 2024-01-19
Today will work on wrists adaptation 5 sets of 30 seconds on the wall.
Belly facing the wall.

It's hard to engage core and lower back. The wrists have a moderate
pressure, because I don't balance much with them.

* 2024-01-21
While the rain is not started yet, trying to do couple handstands and
prepare breakfast.

Did 4 15-20 seconds stands, with one leg touching the wall and couple
attempts of spreaded leg handstand. Around 5 seconds each.

Ok and 1 more attempt of shaky 10 seconds leg spreaded handstand.


* 2024-01-22
Did three very quick handstand attempts.  I'm cold, it's hard.

* 2024-02-08
Did a few attempts, feels quite good, I can stand a bit by pushing off
the wall.  A few times for 3-5 secnonds.
