:PROPERTIES:
:ID:       4bd98aff-0133-4918-aafe-d0abe6278a3f
:END:
#+title: Vomit and Self-Harm

Проблеваться и Сэлфхарм.
Вчера мы бегали с Кристиной, получилось чуть больше 11км, но бегали не по ровному стадиону разумеется, половину времени вообще фигачили в гору по камням, земле и песку. При этом Крис не то чтобы сильно ждала меня на поворотах :) Ну а я не то чтобы хотел стоять прохлождаться и отдыхать; если уж бежать, то бежать всю дистанцию. В какой-то момент времени мне одновременно хотелось блевать и лежать, свернувшись калачиком. Я прошёл через все стадии боли в боку: в левом, в правом, в ключице, под рёбрами. Чуток регулируя темп и дыхание получалось их прожить.

Вообще всё началось с безобидной фразы с Димой некоторое время назад: чё в следующем декабре бежим марафон?  И вроде все понимают, что это шуточный диалог, но моё Я не особо чувствует грань между просто похохмить и закоммититься на 146%.  Своим рацио я конечно осознаю, что это ни к чему не обязывает, особо ни за чем мне не нужно и вообще сказано джаст фо фан, но ангелочек над плечом такой: ты должен ебашить как в последний раз, как-будто от этого зависит жизнь твоя и всех, кто тебе дорог.

Когда-то давно я обсуждал с психологом свои не самые здоровые отношения со спортом. Грусть, печаль, разочарование - от всего убегай на тренировку, упахивайся так, чтобы на мысли не оставалось сил. Вроде эти времена позади, вроде йога, лазание - всё по чуть-чуть, чисто для хорошего самочувствия, грустные мысли все прожиты, а новые появляются крайне редко. Но каждый раз, когда я берусь за что-то, каждый раз, когда прихожу на тернировку: бокс, бег, кубернетес кластер, готовка - не важно, включается режим "умри, но сделай".

Я знаю про это, я ловлю себя на этих моментах, я говорю - побереги свою бренную тушку, пожалей свою уставшую головушку.  А существо, пархающее над вторым плечом такое: ну ты и размазня, канешна, work-life balance, бережное отношение к себе, уты-нуты, какие мы все просветлённые и сознательные.

Кажется ни я один вкурсе про свои эти приколы (:
Стартуй медленно Чередуй бег на время (условно задача бежать как можно дольше в комфортном темпе, пусть даже супер медленно) и бег на небольшие дистанции, 5-7км, и потом наращивай. Главное правило, любая травма и дискомфорт отдаляют тебя от цели сильнее, чем надрыв ради постановки каких-то рекордов приближает.

В общем, листаю пдфку "марафон за 3:15" и сижу выбираю энергетические гели, чтобы обкатать их на тренировочных забегах.
