:PROPERTIES:
:ID:       d86f5c95-e252-4acc-932c-ffdca3059962
:END:
#+title: How to Work


* Intense Work First
Do 2-3 hours of intense work in your most productive hours.  It can
depend on your routine and chronotype.

Going further the mark of a few hours of intense work is non
producitve, it will require tons of willpower to keep focus, but won't
give much benifits.

I even think that restricting the amount of intense work per day is a
good idea.  It will help to stay motivated and focused for weeks or
even years without significant burnouts.

* Combine Intense and Shallow Work
Start from deep important work and when you are out of gas or just
starting to get tired, switch to shallow work.

We need to do some shallow/easy/repetitive work, so it has to be in
our life, but don't start the day with it and don't spend the whole
day doing it for sure.

Also, don't mix shallow and deep work, because shallow work will
become a distraction/easier alternative to deep work.

* Plan the work ahead
Come to the next day knowing, what you will do first in the day.

* Don't think
Define unconditional activity, do it always without questioning and
doubt.  Prepare everything for this task upfront.

* Make distracting thing unaccessible
Put away all the things, which can catch your attention.
