:PROPERTIES:
:ID:       17ae244d-076e-4735-8e67-4e2c952d8465
:END:
#+title: Handstand Diary

* 2024-01-16
I have pretty good physique, but almost no experience with handstand.

I had a lot of attempts (more than 100) to stand, but they were hugely
spreaded in time and I was never focused on this element.

Right now I can stand a few seconds with legs apart a bit.  I feel
weakness in my wrists, which are intensively used for balancing.  When
my lower back bended it becomes hard to balance.  Sperading legs apart
makes it easier to engage the lower back and keep balance.  When there
is a deflection in lower back it's hard to engage core/abdominal
muscles.

Got a coupl seconds of full hand stand, I balance forward with wrist
and backward with bending my elbows.

I take couple minutes between each attempt to fully recover my power.

Bending fingers helps to balance and reduce strain on wrists.

I had quite intensive warmup: https://youtu.be/hgNcfzTxvO8.  Did 5
sets of 10-20 seconds handstand trying to bounce off the wall.  I need
more adaptation in the wrists, probably can reach it by standing in
front of the wall and holding one foot on the wall.
